---
name: ${IMAGE_NAME}
services:
  container:
    image: ${REGISTRY_BASE}/${REGISTRY_PROJECT}/${IMAGE_NAME}:${ROS_DISTRO}-${GITHUB_REF_NAME}
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
      network: host
      pull: true
      no_cache: true
      args:
        # Base image to contruct current image
        image_base_version: ${IMAGE_BASE_VERSION}
        ros_distro: ${ROS_DISTRO}
        base_image: ${REGISTRY_BASE}/robotnik/ros
        version: ${GITHUB_REF_NAME}