---
name: fleet-adapter
services:
  adapter:
    image: fleet-adapter:${ROS_DISTRO}-${VERSION}
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
      args:
        # Base image to contruct current image
        image_base_version: ${IMAGE_BASE_VERSION}
        ros_distro: ${ROS_DISTRO}
        version: ${VERSION}
