---
name: fleet-adapter
services:
  adapter:
    image: fleet-adapter:humble-0.2.0
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
      args:
        # Base image to contruct current image
        image_base_version: a07f857-20231115
        ros_distro: humble
        version: 0.2.0
