---
name: fleet-adapter
services:
  adapter:
    image: fleet-adapter:humble-0.2.1-rc01
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
      args:
        # Base image to contruct current image
        image_base_version: 0.5.0
        ros_distro: humble
        version: 0.2.1-rc01
