---
version: "3.7"
services:
  fleet-adapter:
    image: fleet-adapter:humble-0.1.1-rc02
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    ipc: host
    stop_signal: SIGINT