---
version: "3.7"
services:
  fleet-adapter:
    image: fleet-adapter:humble
    build:
      context: ..
      dockerfile: docker/Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    ipc: host
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      LIBGL_ALWAYS_INDIRECT: 0
    runtime: nvidia
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    devices:
      - "/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stop_signal: SIGINT
    command: >
      sh -c "/ros_entrypoint.sh &&
        ros2 run fleet_adapter_template fleet_adapter -c /home/ros/config/config_rbkairos.yaml -n /home/ros/graph/0.yaml"
