---
version: "3.7"
services:
  fleet-adapter:
    image: fleet-adapter:humble-0.1.0
    build:
      context: ..
      dockerfile: docker/Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    ipc: host
    stop_signal: SIGINT
    command: >
      sh -c "/ros_entrypoint.sh &&
        ros2 run fleet_adapter_template fleet_adapter -c /home/ros/config/config_rbkairos.yaml -n /home/ros/graph/0.yaml"
