---
name: fleet-adapter
services:
  adapter:
    image: fleet-adapter:humble-devel
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      FLEET_CONFIG_FILE: /home/robot/config/config_rbkairos.yaml
      GRAPH_CONFIG_FILE: /home/robot/graph/0.yaml
