# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "robotnik_fleet"
  fleet_manager:
    broker: "localhost"
    port: 1883
    keep_alive: 60
    anonymous_access: true
    user: "some_user"
    password: "some_password"
    pose_topic: "pose/#"
    feedback_topic: "feedback/#"
    result_topic: "result/#"
    battery_topic: "battery/#"
    distance: 0.5
  limits:
    linear: [3, 3] # velocity, acceleration
    angular: [3, 3] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.75 # radius in m
    vicinity: 0.5 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 26.4 # A
  mechanical_system:
    mass: 80.0 # kg
    moment_of_inertia: 20.0 #kgm^2
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 760.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: True
  account_for_battery_drain: False
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    patrol: True
    finishing_request: "nothing" # [park, charge, nothing]
    action_categories: ["teleop"]
  lane_merge_distance: 0.5
  waypoint_merge_distance: 0.5
  filer_waypoints: True

# Custom robot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  robot_a:
    robot_config:
      fleet: "robotnik_fleet" # API endpoint for the robot
      max_delay: 5.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5
      start:
        map_name: "robot_map"
        waypoint: "parking1"
        orientation: 0.0
      charger:
        waypoint: "parking1"
  robot_b:
    robot_config:
      fleet: "robotnik_fleet" # API endpoint for the robot
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5
      start:
        map_name: "robot_map"
        waypoint: "parking2"
        orientation: 0.0
      charger:
        waypoint: "parking1"
  robot_c:
    robot_config:
      fleet: "robotnik_fleet" # API endpoint for the robot
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5
      start:
        map_name: "robot_map"
        waypoint: "parking3"
        orientation: 0.0
      charger:
        waypoint: "parking1"
  robot_d:
    robot_config:
      fleet: "robotnik_fleet" # API endpoint for the robot
      max_delay: 40.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5
      start:
        map_name: "robot_map"
        waypoint: "parking4"
        orientation: 0.0
      charger:
        waypoint: "parking1"
  robot_e:
    robot_config:
      fleet: "robotnik_fleet" # API endpoint for the robot
      max_delay: 30.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5
      start:
        map_name: "robot_map"
        waypoint: "parking5"
        orientation: 0.0
      charger:
        waypoint: "parking1"

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

reference_coordinates:

  rmf: [[59.64, -51.144],
        [59.69, -38.946],
        [40.09, -38.99],
        [40.09, -51.19]]

  robot: [[9.25, -1.93],
        [9.51, 10.24],
        [-9.83, 10.17],
        [-9.88, -1.97]]
